apiVersion: v1
kind: Service
metadata:
  name: local-service
  namespace: yahoo
  labels:
    app: local-test
spec:
  ports:
  - port: 3306
    name: local-port
  clusterIP: None
  selector:
    app: local-test
